name: Susan's Photo Dump
favicon: null
layout_spectrum: 0.99527
typography_spectrum: 0.49527
title: Susan's Photo Dump
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#c2beb3'
    - '#fefefe'
    - '#090909'
    - '#31616f'
    - '#5c4123'
  brandStrength: 0.125
  lightness: 0.6875
  saturation: 1
  rhythmicContrast: 0
purpose: []
