typography_spectrum: 0.16542
content_rating:
  adult: false
color:
  brandColors:
    - '#c2beb3'
    - '#fefefe'
    - '#090909'
    - '#31616f'
    - '#5c4123'
  brandStrength: 0.125
  lightness: 0.6875
  saturation: 1
  rhythmicContrast: 0
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 1
analytics:
  google: null
  facebook: null
  twitter: null
author:
  name: Susan Adams
  email: susanad813@gmail.com
  url: SusanEAdams.com
name: Susan's Photo Dump
cta:
  domain: null
  bucket: null
  version: null
favicon: null
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
title: Susan's Photo Dump
description: learning to use the Grid
purpose: []
