name: "Susan's Photo Dump"
favicon: null
layout_spectrum: 0.99875
typography_spectrum: 0.0631
title: "Susan's Photo Dump"
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#04070c'
    - '#858e97'
    - '#f7f4ef'
    - '#50483e'
    - '#d99557'
  brandStrength: 0.5
  lightness: 0.875
  saturation: 1
  rhythmicContrast: 0.25
purpose: []
