name: "Susan's Photo Dump"
favicon: null
layout_spectrum: 0.24952
typography_spectrum: 0
title: "Susan's Photo Dump"
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#8a606a'
    - '#d3bdb0'
    - '#c28a82'
    - '#482529'
    - '#9b797d'
  brandStrength: 0.918233924312517
  lightness: 0.9445746312849224
  saturation: 0.288964954437688
  rhythmicContrast: 0.3506765274796635
purpose: []
