title: "Susan's Photo Dump"
purpose: []
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
color:
  saturation: 1
  brandStrength: 0
  lightness: 0.7702128
  brandColors:
    - '#f9f5ea'
    - '#d9ceae'
    - '#808780'
    - '#2c4b66'
    - '#000000'
  rhythmicContrast: 0.8276595
cta:
  bucket: null
  version: null
  domain: null
analytics:
  twitter: null
  google: null
  facebook: null
favicon: null
name: "Susan's Photo Dump"
opengraph:
  image: null
  type: null
  appId: null
typography_spectrum: 0
layout_spectrum: 0.99875
